Task Trello HTML template
lukarta842/chronometer pull request #1
Opened 2023-01-11 16:27 UTC by lukarta842

2023-01-11 17:41 UTC, mcaria requested changes

2023-01-11 17:41 UTC, mcaria commented on public/index.html
> +      <div id="displayContainer">
Il tag H3 è superfluo, basta il div displayContainer. 
Rimuoverei gli span e gestirei il timer come stringa dentro un unico tag p in modo da gestire agevolmente le ore, i minuti ed i secondi come array facendo uno split della stringa sui :. 

Per il resto 👍

2023-01-11 20:26 UTC, lukarta842 commented on public/index.html
> +      <div id="displayContainer">
Grazie, procedo

2023-01-12 08:10 UTC, mcaria approved these changes
💯

2023-01-12 08:11 UTC, merged